import { boolean, numeric, pgTable, text, timestamp, unique } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const wallet = pgTable('wallet', { id: text('id').primaryKey(), userId: text('userId').notNull(), address: text('address').notNull().unique(), network: text('network').notNull().default('mainnet-beta'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const strategy = pgTable('strategy', { id: text('id').primaryKey(), userId: text('userId').notNull(), name: text('name').notNull(), enabled: boolean('enabled').notNull().default(false), maxPositionUsd: numeric('maxPositionUsd').notNull().default('0'), stopLossPct: numeric('stopLossPct').notNull().default('0'), takeProfitPct: numeric('takeProfitPct').notNull().default('0'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const watchlist = pgTable('watchlist', { id: text('id').primaryKey(), userId: text('userId').notNull(), symbol: text('symbol').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() }, (t) => [unique().on(t.userId, t.symbol)])
